// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6QfAQhqtkSf8tGwotz_eO4_65AG6CYdQ',
    appId: '1:906786565790:web:7e2da6455f6ea65a3d958f',
    messagingSenderId: '906786565790',
    projectId: 'pet-info-project',
    authDomain: 'pet-info-project.firebaseapp.com',
    storageBucket: 'pet-info-project.appspot.com',
    measurementId: 'G-6TR16Y1KDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MdQKv4_n7ZuRZUXtnHw3qupchGCLgcI',
    appId: '1:906786565790:android:6d9ec1a925543eca3d958f',
    messagingSenderId: '906786565790',
    projectId: 'pet-info-project',
    storageBucket: 'pet-info-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5PfaUf3YFlT15sFadz8u2Dupq-9eTK8',
    appId: '1:906786565790:ios:d4ed464cdccfd1103d958f',
    messagingSenderId: '906786565790',
    projectId: 'pet-info-project',
    storageBucket: 'pet-info-project.appspot.com',
    iosBundleId: 'com.example.petinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU5PfaUf3YFlT15sFadz8u2Dupq-9eTK8',
    appId: '1:906786565790:ios:d4ed464cdccfd1103d958f',
    messagingSenderId: '906786565790',
    projectId: 'pet-info-project',
    storageBucket: 'pet-info-project.appspot.com',
    iosBundleId: 'com.example.petinfo',
  );
}
